### ISSUE TITLE
EcoSkills

### ISSUE THREAD

**Issue by KaspianDev** [mfnalex/Community-Survival#6]
Yea it's OSS and well um it adds skills so you dont get bored even when doing boring tasks and its not too op.
https://github.com/Auxilor/EcoSkills

**Comment by mfnalex** [comment]
I'd rather use mcmmo instead. but i guess most people would be against that

**Comment by KaspianDev** [comment]
> I'd rather use mcmmo instead. but i guess most people would be against that

mcmmo still lives in 2014 and doesn't get new features. Aureliumskills is supossed to be a replacement while ecoskills is something else.
If you want mcmmo, use aureliumskills.
