### ISSUE TITLE
Voice chat with no mods!

### ISSUE THREAD

**Issue by KaspianDev** [mfnalex/Community-Survival#8]
This plugin https://www.spigotmc.org/resources/openaudiomc-proximity-voice-chat-realtime-music-no-mods.30691/ adds web based distance based chat. truly cool (i used it on smp with my broskies)

**Comment by cxlina** [comment]
I wouldn't use it anyway.

**Comment by KaspianDev** [comment]
i dont like staying in 1 place just for creeper to kill me while typing

**Comment by ImajinDevon** [comment]
i woudlnt use it

**Comment by KaspianDev** [comment]
bruh yall scared of humans

**Comment by mfnalex** [comment]
Indeed.
